name: CI

on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - 'v*'
    # always run CI for tags
    tags:
      - '*'

  # early issue detection: run CI weekly on Sundays
  schedule:
    - cron: '0 6 * * 0'

env:
  CI: true

jobs:
  test-locked-deps:
    name: Locked Deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: volta-cli/action@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: lint:js
        run: yarn lint:js
      - name: lint:hbs
        run: yarn lint:hbs
      - name: Browser Tests
        run: yarn test

  test-try:
    name: Ember Try
    runs-on: ubuntu-latest
    needs: [test-locked-deps]
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-release
          - ember-beta
          - ember-default-with-jquery
          - ember-classic
          - embroider-safe
          - embroider-optimized
        experimental: [false]
        include:
          - scenario: ember-canary
            experimental: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
      - name: Install Node
        uses: volta-cli/action@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Try Scenario
        run: yarn ember try:one ${{ matrix.scenario }}
